### ISSUE TITLE
Trying to create HTTPS and websocket not converting to wss

### ISSUE THREAD

**Issue by yestrdave** [hucknz/cumulusmx#4]
@hucknz thank you so much for this great work.  I love this docker image.  So much so it created my problem.  Rather than recreate the dashboard in Home Assistant I used IFrames and due to the HTTP clashing inside HA with the HTTPS site is on - it wont  display. (I believe this is a standard error for anytime they dont match, not just HA)  I created a Reverse Proxy and set it up what I believe is correct.  I really just need this to run local under HTTPS to use the dashboard.  Im stuck at the moment and at my knowledge limit on this subject.  Here is a summary of my set up.

### Hardware** & Host OS
NAS: Synology RS822+
DSM: 7.2.2-72806 Update 3

### Cumulus MX (Docker)
Image: hucknz/cumulusmx:latest
Compose file (docker-compose.yml, version 3.8):

```
services:
  cumulus_mx:
    image: hucknz/cumulusmx:latest
    container_name: cumulus_mx_compose
    restart: unless-stopped
    network_mode: bridge    # also tested host mode
    ports:
      - "22222:22222/udp"
      - "8998:8998"
    volumes:
      - /volume1/docker/cumulusmx/config:/opt/CumulusMX/config:rw
      - /volume1/docker/cumulusmx/data:/opt/CumulusMX/data:rw
      - /volume1/docker/cumulusmx/mqtt:/opt/CumulusMX/mqtt:rw
    environment:
      - TZ=America/New_York
    working_dir: /opt/CumulusMX
    entrypoint: ["./MXWeather.sh"]
```
### Synology Reverse Proxy
Control Panel → Application Portal → Reverse Proxy
Rule name: weather

### Source:
Protocol: HTTPS
Hostname: weather.yestrdave.com
Port: 443

### Destination:
Protocol: HTTP
Hostname: localhost
Port: 8998

### Custom Header (manually added):
Upgrade: $http_upgrade
Connection: $connection_upgrade

### Advanced Settings:
Proxy HTTP version: HTTP 1.1

When loading https://weather.yestrdave.com, DevTools shows:
```
Mixed Content: The page at ‘https://weather.yestrdave.com/’ was loaded over HTTPS,
but attempted to connect to the insecure WebSocket endpoint
‘ws://weather.yestrdave.com:8998/ws’. This request has been blocked;
this endpoint must be available over WSS.
```
`Uncaught SecurityError: Failed to construct ‘WebSocket’: An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`
